# Generated by Django 5.0.7 on 2024-07-25 06:30

from django.db import migrations

def seed_data(apps, schema_editor):
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')

    # Create a store
    kimbap_store = Store.objects.create(name="김밥천국 중앙점", description="맛있는 김밥 전문점")

    # Create menu items
    MenuItem.objects.create(store=kimbap_store, name="원조김밥", price=3500)
    MenuItem.objects.create(store=kimbap_store, name="참치김밥", price=4500)
    MenuItem.objects.create(store=kimbap_store, name="치즈김밥", price=4000)

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]