# Generated by Gemini

from django.db import migrations

def seed_franchise_data(apps, schema_editor):
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')

    # 1. 메가MGC커피 천안나사렛대점
    mega_coffee = Store.objects.create(name="메가MGC커피 천안나사렛대점", description="나사렛대학교 근처의 메가MGC커피")
    
    MenuItem.objects.create(store=mega_coffee, name="아메리카노 (ICE)", price=3500)
    MenuItem.objects.create(store=mega_coffee, name="카페라떼 (ICE)", price=4700)
    MenuItem.objects.create(store=mega_coffee, name="바닐라라떼 (ICE)", price=5200)
    MenuItem.objects.create(store=mega_coffee, name="쿠키프라페", price=5800)
    MenuItem.objects.create(store=mega_coffee, name="레몬에이드", price=5200)
    MenuItem.objects.create(store=mega_coffee, name="딸기바나나주스", price=3800)

    # 2. 컴포즈커피 천안용암마을점
    compose_coffee = Store.objects.create(name="컴포즈커피 천안용암마을점", description="나사렛대학교 근처의 컴포즈커피")

    MenuItem.objects.create(store=compose_coffee, name="아메리카노", price=2500)
    MenuItem.objects.create(store=compose_coffee, name="카페라떼", price=3900)
    MenuItem.objects.create(store=compose_coffee, name="더블초코라떼", price=4500)
    MenuItem.objects.create(store=compose_coffee, name="리얼초코자바칩 프라페", price=5000)
    MenuItem.objects.create(store=compose_coffee, name="자몽에이드", price=4500)
    MenuItem.objects.create(store=compose_coffee, name="복숭아티", price=4000)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seed_initial_data'),
    ]

    operations = [
        migrations.RunPython(seed_franchise_data),
    ]
