# Generated by Gemini

from django.db import migrations

def correct_price(apps, schema_editor):
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')
    
    try:
        # Find the specific store and menu item
        mega_coffee_store = Store.objects.get(name="메가MGC커피 천안나사렛대점")
        americano = MenuItem.objects.get(store=mega_coffee_store, name="아메리카노 (ICE)")
        
        # Update the price
        if americano.price != 2000:
            americano.price = 2000
            americano.save()
            
    except Store.DoesNotExist:
        # Handle case where store might not exist
        pass
    except MenuItem.DoesNotExist:
        # Handle case where menu item might not exist
        pass

def revert_price(apps, schema_editor):
    # This function allows the migration to be reversible
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')

    try:
        mega_coffee_store = Store.objects.get(name="메가MGC커피 천안나사렛대점")
        americano = MenuItem.objects.get(store=mega_coffee_store, name="아메리카노 (ICE)")
        
        # Revert to the old price
        americano.price = 3500
        americano.save()

    except Store.DoesNotExist:
        pass
    except MenuItem.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_seed_franchise_data'),
    ]

    operations = [
        migrations.RunPython(correct_price, reverse_code=revert_price),
    ]
