# Generated by Gemini

from django.db import migrations

def correct_all_prices(apps, schema_editor):
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')
    
    # Mega MGC Coffee
    try:
        mega_coffee_store = Store.objects.get(name="메가MGC커피 천안나사렛대점")
        
        # Update prices for Mega Coffee
        menu_items_to_update = {
            "아메리카노 (ICE)": 2000,
            "카페라떼 (ICE)": 2900,
            "바닐라라떼 (ICE)": 3400,
            "쿠키프라페": 3900,
            "레몬에이드": 3500,
            "딸기바나나주스": 5200,
        }
        for item_name, new_price in menu_items_to_update.items():
            menu_item = MenuItem.objects.get(store=mega_coffee_store, name=item_name)
            if menu_item.price != new_price:
                menu_item.price = new_price
                menu_item.save()
                
    except Store.DoesNotExist:
        pass
    except MenuItem.DoesNotExist:
        pass # Log this in a real app

    # Compose Coffee
    try:
        compose_coffee_store = Store.objects.get(name="컴포즈커피 천안용암마을점")

        # Update prices for Compose Coffee
        menu_items_to_update = {
            "아메리카노": 1800,
            "카페라떼": 2900,
            "더블초코라떼": 4000,
            "리얼초코자바칩 프라페": 4500,
            "자몽에이드": 4000,
            "복숭아티": 3000,
        }
        for item_name, new_price in menu_items_to_update.items():
            menu_item = MenuItem.objects.get(store=compose_coffee_store, name=item_name)
            if menu_item.price != new_price:
                menu_item.price = new_price
                menu_item.save()

    except Store.DoesNotExist:
        pass
    except MenuItem.DoesNotExist:
        pass # Log this in a real app


def revert_all_prices(apps, schema_editor):
    # This function allows the migration to be reversible
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')

    # Revert Mega MGC Coffee prices to previous values (from 0003_seed_franchise_data)
    try:
        mega_coffee_store = Store.objects.get(name="메가MGC커피 천안나사렛대점")
        menu_items_to_revert = {
            "아메리카노 (ICE)": 3500,
            "카페라떼 (ICE)": 4700,
            "바닐라라떼 (ICE)": 5200,
            "쿠키프라페": 5800,
            "레몬에이드": 5200,
            "딸기바나나주스": 3800,
        }
        for item_name, old_price in menu_items_to_revert.items():
            menu_item = MenuItem.objects.get(store=mega_coffee_store, name=item_name)
            if menu_item.price != old_price:
                menu_item.price = old_price
                menu_item.save()
    except Store.DoesNotExist:
        pass
    except MenuItem.DoesNotExist:
        pass

    # Revert Compose Coffee prices to previous values (from 0003_seed_franchise_data)
    try:
        compose_coffee_store = Store.objects.get(name="컴포즈커피 천안용암마을점")
        menu_items_to_revert = {
            "아메리카노": 2500,
            "카페라떼": 3900,
            "더블초코라떼": 4500,
            "리얼초코자바칩 프라페": 5000,
            "자몽에이드": 4500,
            "복숭아티": 4000,
        }
        for item_name, old_price in menu_items_to_revert.items():
            menu_item = MenuItem.objects.get(store=compose_coffee_store, name=item_name)
            if menu_item.price != old_price:
                menu_item.price = old_price
                menu_item.save()
    except Store.DoesNotExist:
        pass
    except MenuItem.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_correct_mega_coffee_price'), # Depend on the previous correction
    ]

    operations = [
        migrations.RunPython(correct_all_prices, reverse_code=revert_all_prices),
    ]
