
# Generated by Django 5.0.6 on 2024-05-23 12:00

from django.db import migrations

def add_more_franchises(apps, schema_editor):
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')

    # Lotteria data
    lotteria = Store.objects.create(name='롯데리아', description='대한민국 대표 패스트푸드 프랜차이즈')
    MenuItem.objects.create(store=lotteria, name='불고기버거', price=4500)
    MenuItem.objects.create(store=lotteria, name='새우버거', price=4500)
    MenuItem.objects.create(store=lotteria, name='데리버거', price=3000)
    MenuItem.objects.create(store=lotteria, name='치즈스틱', price=2000)

    # Mom's Touch data
    moms_touch = Store.objects.create(name='맘스터치', description='치킨 및 수제버거 전문 프랜차이즈')
    MenuItem.objects.create(store=moms_touch, name='싸이버거', price=4600)
    MenuItem.objects.create(store=moms_touch, name='인크레더블버거', price=5700)
    MenuItem.objects.create(store=moms_touch, name='케이준떡강정', price=3500)

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_correct_all_prices'),
    ]

    operations = [
        migrations.RunPython(add_more_franchises),
    ]
