# Generated by Gemini
from django.db import migrations

def seed_momstouch_data(apps, schema_editor):
    Store = apps.get_model('orders', 'Store')
    MenuItem = apps.get_model('orders', 'MenuItem')

    # 3. 맘스터치 천안쌍용점
    momstouch_store = Store.objects.create(name="맘스터치 천안쌍용점", description="나사렛대학교 근처의 맘스터치")
    
    MenuItem.objects.create(store=momstouch_store, name="싸이버거", price=4600)
    MenuItem.objects.create(store=momstouch_store, name="그릴드비프버거", price=5100)
    MenuItem.objects.create(store=momstouch_store, name="불고기버거", price=3900)
    MenuItem.objects.create(store=momstouch_store, name="케이준떡강정", price=3500)
    MenuItem.objects.create(store=momstouch_store, name="후라이드치킨(반마리)", price=10000)
    MenuItem.objects.create(store=momstouch_store, name="콜라", price=1800)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_more_franchises'),
    ]

    operations = [
        migrations.RunPython(seed_momstouch_data),
    ]
