# Generated by Django 5.2 on 2025-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_add_momstouch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '주문중'), ('awaiting_payment', '결제 대기'), ('completed', '주문 완료'), ('cancelled', '주문 취소')], default='pending', max_length=20),
        ),
    ]
